// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shopping.API.Data;

namespace Shopping.API.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20210908223300_AddProductEntity")]
    partial class AddProductEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Shopping.API.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Description");

                    b.Property<string>("ImageFile");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Category = "Smart Phone", Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.", ImageFile = "product-1.png", Name = "IPhone X", Price = 950.00m },
                        new { Id = 2, Category = "Smart Phone", Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.", ImageFile = "product-2.png", Name = "Samsung 10", Price = 840.00m },
                        new { Id = 3, Category = "White Appliances", Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.", ImageFile = "product-3.png", Name = "Huawei Plus", Price = 650.00m },
                        new { Id = 4, Category = "White Appliances", Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.", ImageFile = "product-4.png", Name = "Xiaomi Mi 9", Price = 470.00m },
                        new { Id = 5, Category = "Smart Phone", Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.", ImageFile = "product-5.png", Name = "HTC U11+ Plus", Price = 380.00m },
                        new { Id = 6, Category = "Home Kitchen", Description = "This phone is the company's biggest change to its flagship smartphone in years. It includes a borderless.", ImageFile = "product-6.png", Name = "LG G7 ThinQ EndofCourse", Price = 240.00m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
